trigger: 
  - none 

pool:  
  vmImage: ubuntu-latest 

variables:
  buildConfiguration: 'Release'

steps: 
- task: DotNetCoreCLI@2
  inputs: 
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs: 
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildconfiguration)'

- task: PublishBuildArtifacts@1
  inputs: 
    PathtoPublish: '$(build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'